kind: Service
apiVersion: v1
metadata:
  name:  mysql
  labels:
    app: cyo-practica2
  namespace: default
spec:
  selector:
    app: cyo-practica2
    server: mysql
  type:  ClusterIP
  ports:
  - port:  3306
    targetPort:  3306

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: cyo-practica2
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: cyo-practica2
        server: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass
        volumeMounts:
        - name:  pvc-mysql-500m
          mountPath:  /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name:  pvc-mysql-500m
        persistentVolumeClaim:
            claimName: pvc-mysql-500m

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql-500m
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/Users/fran/db/mysql"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mysql-500m
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi