{{- if .Values.networkPolicies.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "practica4.name" . }}-default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "practica4.name" . }}-allow-server-to-mongo
spec:
  podSelector:
    matchLabels:
      {{ include "practica4.selectorLabels" . | nindent 6 }}
      server: mongo
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "practica4.selectorLabels" . | nindent 12 }}
            server: server
      ports:
      - protocol: TCP
        port: 27017

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "practica4.name" . }}-allow-server-to-rabbit
spec:
  podSelector:
    matchLabels:
      {{ include "practica4.selectorLabels" . | nindent 6 }}
      server: rabbitmq
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "practica4.selectorLabels" . | nindent 12 }}
            server: server
      ports:
      - protocol: TCP
        port: 5672

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "practica4.name" . }}-allow-worker-to-rabbit
spec:
  podSelector:
    matchLabels:
      {{ include "practica4.selectorLabels" . | nindent 6 }}
      server: rabbitmq
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "practica4.selectorLabels" . | nindent 12 }}
            server: worker
      ports:
      - protocol: TCP
        port: 5672

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "practica4.name" . }}-allow-worker-to-mysql
spec:
  podSelector:
    matchLabels:
      {{ include "practica4.selectorLabels" . | nindent 6 }}
      server: mysql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "practica4.selectorLabels" . | nindent 12 }}
            server: worker
      ports:
      - protocol: TCP
        port: 3306

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "practica4.name" . }}-allow-worker-to-externalservice
spec:
  podSelector:
    matchLabels:
      {{ include "practica4.selectorLabels" . | nindent 6 }}
      server: externalservice
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "practica4.selectorLabels" . | nindent 12 }}
            server: worker
      ports:
      - protocol: TCP
        port: 8082
{{- end -}}