kind: Service
apiVersion: v1
metadata:
  name:  mongo
  labels:
    app: cyo-practica2
  namespace: default
spec:
  selector:
    app:  cyo-practica2
    server: mongo
  type:  ClusterIP
  ports:
  - port:  27017
    targetPort:  27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: cyo-practica2
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: cyo-practica2
        server: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort: 27017
      restartPolicy: Always