package models;

public enum Error {
    BACKWARD_MOVEMENT,
    NOT_DIAGONAL_MOVEMENT,
    EMPTY_SQUARE,
    CAPTURE_NOT_ALLOWED,
    NOT_EMPTY_SQUARE,
    TOO_MUCH_CAPTURED_PIECES,
    NOT_MOVEMENT
}
